---
name: milvus
channels:
  - conda-forge
dependencies:
  - cmake>=3.18
  - c-compiler
  - cxx-compiler
  - docker-compose
  - gcc_linux-64=9.*
  - go>=1.18
  - grpcio=1.47.0
  - libblas
  - make
  - pip
  - ninja
  - pip:
      - conan==1.59.0
